version: '3.8'

services:
  web:
    build: .
    container_name: aicaptcha_web
    restart: always
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
    ports:
      - '5000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.aicaptcha.rule=Host(`aicaptcha.local`)' 
      - 'traefik.http.routers.aicaptcha.entrypoints=web'
      - 'traefik.http.routers.aicaptcha.entrypoints=websecure'
      - 'traefik.http.routers.aicaptcha.tls.certresolver=myresolver'
    volumes:
      - .:/app
    command: python3 main.py

  traefik:
    image: traefik:v2.5
    container_name: traefik
    restart: always
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.myresolver.acme.email=your-email@example.com'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
      - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
      - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt